### ISSUE TITLE
Houston, we have a problem. Fancy Portals Broken. 

### ISSUE THREAD

**Issue by neoshifter39** [iChun/IssueTracker-Mods#106]
Hey this didn't happen before. now I Re-installed The mod and this. Can confirm I'm not the only one.
![2017-08-02_00 13 05](https://user-images.githubusercontent.com/30562642/28873823-2d616918-775d-11e7-8244-6aca1c10e083.png)
![2017-08-02_00 13 10](https://user-images.githubusercontent.com/30562642/28873827-3437ec1c-775d-11e7-96c7-e1e5a8fe0a40.png)
![2017-08-02_00 13 20](https://user-images.githubusercontent.com/30562642/28873828-35b8af4a-775d-11e7-9069-5c2750edf39a.png)
![2017-08-02_00 14 55](https://user-images.githubusercontent.com/30562642/28873831-37eb9de0-775d-11e7-8c03-0299ece520ce.png)

**Comment by Aang23** [comment]
Same problem here.

**Comment by iChun** [comment]
@modmuss50 reports this is fixed in version 7.0.1. Reopen a new issue if it's not
