### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by Iceflame3029** [iChun/IssueTracker-Mods#110]
Could you please put the code of Gravity Gun Mod and Portal Gun Mod on GitHub?

**Comment by iChun** [comment]
No, sorry. They're being kept closed source for a reason. However, most of their main functionality is in iChunUtil, which is open source. https://github.com/iChun/iChunUtil

**Comment by Sanduhr32** [comment]
Reason = son of a bitch that doesnt like a community supporting him? yes good reason
