### ISSUE TITLE
[1.12.2][Portal Gun][Gravity Gun] Grabbing Block Animation Broken

### ISSUE THREAD

**Issue by Cyastis** [iChun/IssueTracker-Mods#112]
Using the "Latest" Forge for 1.12.2 (build 2495 through build 2501) and Portal Gun 7.0.0 iChunUtil 7.0.0 or Gravity Gun 7.0.0 the grab animation for blocks is nonexistent. NVIDIA Geforce GTX 1070 (mobile non-MAX-Q) was used. The block seem to disappear once grabbed and reappear after being let go. The physics appear to remain entirely intact. What was expected to happen was the grab animation to appear and the block to not become invisible. File Attached. Previous report closed for being on the incorrect issue tracker. Thank you!

[Minecraft 1.12.2 10_2_2017 9_28_23 PM.zip](https://github.com/iChun/IssueTracker-Mods/files/1351036/Minecraft.1.12.2.10_2_2017.9_28_23.PM.zip)

**Comment by iChun** [comment]
This happens with gravity gun too? I'll test when I can.

**Comment by Cyastis** [comment]
Not tested, as I have not downloaded the mod. There’s a small chance it’s configuration dependent,  I will test it tomorrow when I can.

**Comment by iChun** [comment]
They both use the same system and the same entity so there's a high chance
it might happen as well. I have to double check

**Comment by Cyastis** [comment]
Suspicions confirmed, Gravity Gun mod is affected. However, it seems that for both the Portal Gun and the Gravity Gun, the animation is only broken for blocks, not entities. Will change description to reflect findings.

**Comment by iChun** [comment]
Found the issue already and fixed in in dev. Gonna try and drop a few
releases later today.

**Comment by iChun** [comment]
Fixed in iChunUtil 7.0.1
