### ISSUE TITLE
[1.12.1] Minecraft refuses to launch because of MC version

### ISSUE THREAD

**Issue by Peca21** [iChun/IssueTracker-Mods#113]
Portal and gravity gun have 1.12.1 as the compatible version on curse but 1.12.1 minecraft refuses to launch because both mods require 1.12.2.

https://i.imgur.com/L6LwrAW.png
https://i.imgur.com/gDBSMal.png

**Comment by iChun** [comment]
An update will be released later today to address this

**Comment by iChun** [comment]
Releases are out. Have fun.
