### ISSUE TITLE
[AttachableGrinder] mcmod.info file :P

### ISSUE THREAD

**Issue by xJon** [iChun/IssueTracker-Mods#12]
The 4.0.0 version (and possibly the 3.0.0 version too) has the wrong version in it, "2.0.0".
just want to be sure that you're aware. :)
Thanks for the great mods iChun, keep up the good work.

**Comment by iChun** [comment]
Bit old, but should mention that it's been fixed anyways.

**Comment by xJon** [comment]
:)
