### ISSUE TITLE
Feature Request: Square Portals

### ISSUE THREAD

**Issue by KetHalpak** [iChun/IssueTracker-Mods#123]
Hey iChun,
Would it be at all possible to have an option/attribute in the portal gun for square shaped (full block sized) portals?

I've always wanted to make a base that gets the non-euclidian geometry bit nailed down with the trippy visuals, having the portals fit snugly with normal minecraft block sizes would just make it perfect!

**Comment by iChun** [comment]
This would require another mod, really. Have you seen my new recent mod called GLASS though? https://minecraft.curseforge.com/projects/general-laymans-aesthetic-spying-screen-glass

These don't let you teleport however. I've been thinking of making an actual WorldPortals mod but it'll be fairly complicated for the end user (trust me when I say this) but I have a larger priority of fixing the rendering first.

**Comment by iChun** [comment]
Also I see you're an Animorphs fan. I scrolled up and did a double take when I saw your username.

**Comment by KetHalpak** [comment]
Your the only person in 15 years to get the reference!

I've been having fun playing around with glass, it got me back onto thinking about square portals again, so figured it was worth asking the question. Thanks for getting back so quickly.

**Comment by iChun** [comment]
Geez has it really been 15 years? You've just made me feel old now. (psst: Morph was named as morph largely because of Animorphs' influence)
