### ISSUE TITLE
I don't know if it's a problem with the mod or my PC ( I have a laptop Dell with an i7 i think 3rd gen and a geforce 920m)

### ISSUE THREAD

**Issue by DLordStarkiller** [iChun/IssueTracker-Mods#133]
So I have been using the portal gun mod for quite a long time now. But today I downloaded the newest version for 1.10.2. So I place the first portal and everything is fine but the moment I place the second one my game crashes! Is there anything I can do to change it or is it a mod problem?

**Comment by DLordStarkiller** [comment]
Ok, I found it it was the shading!!!!!

**Comment by DLordStarkiller** [comment]
well it was the usage of both rendering through the portal and fancy portals

**Comment by TNTUP** [comment]
Same issue here, no shaders, have Optifine. Client crashes. Disabling     I:seeThroughPortals=0 solves the problem. Can provide the logs if requested

**Comment by sp614x** [comment]
Latest OptiFine preview D1 for 1.12.2 should work with see-through portals.
