### ISSUE TITLE
Portal Gun does not work when any item is held in the offhand

### ISSUE THREAD

**Issue by bl4ckscor3** [iChun/IssueTracker-Mods#136]
How to reproduce: Hold an item in your offhand and the Portal Gun in your main hand. Try creating a portal, nothing will happen.
Portal Gun 7.0.2, iChunUtil 7.1.4, Minecraft 1.12.2

**Comment by iChun** [comment]
It's as intended. Portal Guns and Gravity Guns are *two handed* items. Having an item in off hand will prevent you from using it. The item render is lowered and bent to the side to notify the player that you can't use the item.
