### ISSUE TITLE
[PortalGun] [1.12.2-7.0.2] Multiple right-click portals can be spawned if a portal is left open in another dimension

### ISSUE THREAD

**Issue by evknucklehead** [iChun/IssueTracker-Mods#143]
Was playing around with the Portal Gun in my Foolcraft 3 install (pack version 1.2.0, Portal Gun mod version 7.0.2) when I noticed some weird behavior with the portals. Every time I right clicked a new portal would spawn, but it wouldn't link to a left-click portal unless one was spawned before the right-click portal. Any additional right-click portals would remain until all portals were cleared, while the left-click portals would replace the old ones as expected. Additionally, closing the portals would leave one side of the HUD overlay showing an open portal, depending on which portal was last placed.

I realized that I had left a pair of portals open in the Nether, so I went there to close them and tried again, and everything was back to normal. I then left a pair open in the overworld, and was able to spawn multiple right-click portals in the nether, with the same requirement of having a left-click portal active before linking.

Hopefully we'll be back to the way it was back in 1.7.10, where we could have portals open from the same gun in multiple dimensions independent of each other, as it was great for leaving quick shortcuts back to my base.

**Comment by iChun** [comment]
Hacky fix implemented in 7.1.0.... I think!. I'll do a proper fix when the mod comes round to 1.13.
