### ISSUE TITLE
[PortalGun] Server crashes at random (FTB v1.12.2 Multiplayer)

### ISSUE THREAD

**Issue by TheOpalium** [iChun/IssueTracker-Mods#145]
Heya.

I'm running an FTB server with Direwolf20's pack for myself and a few friends. Every once in a while, however, the server crashes at random with what seems to be an error in the mod.

Here's the crash log: https://pastebin.com/9DPHx5Gm
An interesting point is that this seems to happen even if the portal gun is not used at all. I have banned the item completely from the server to see if it helps (it's unusable by anyone currently), yet this crash still happens.

Ubuntu 16.04 64bit, OpenJDK 8. I'm using the stock Direwolf20 modpack with the addition of VivecraftForge. Oh, and Sponge with a management pack (Nucleus and LuckPerms).

Your help is very much appreciated!
~Opalium

**Comment by iChun** [comment]
Update portal gun. I fixed that crash a while back.

**Comment by TheOpalium** [comment]
Thank you. 😄
