### ISSUE TITLE
1.12.2 Portal Gun doesn't work beyond 10000 blocks away from 0,0

### ISSUE THREAD

**Issue by combustionsquirrel** [iChun/IssueTracker-Mods#147]
Minecraft version: 1.12.2
Forge: 2739
Mod Version: 7.0.2
Multiplayer
Custom modpack
<details>
<summary>Modlist</Summary>
/Dank/null - 
Abyssalcraft - 
Actually Additions - 
Akashic Tome - 
Appleskin - 
Applied Energistics 2 - 
Aroma1997 Dimensional World - 
Astral Sorcery - 
AutoRegLib - 
Bad wither no cookie - 
Baubles - 
Batter Advancements - 
Better Builders Wands - 
Bibliocraft - 
Biomes O Pleanty - 
Blockcrafty - 
Blood Magic Bookshelf - 
Botania - 
Brandon's Core - 
Chameleon - 
Chicken Chunks 1.8+  - 
Chisel - 
Chisels & Bits - 
CoFH Core - 
CoFH World - 
Colossal Chests - 
Common Capabilities - 
Compact Machines - 
ConnectedTexturesMod - 
Construct's Armory - 
Controlling - 
Cooking for Blockheads - 
CraftTweaker - 
Custom Main Menu - 
Cyclic - 
Cyclops Core - 
Dark Utilites - 
Default Options - 
Diet Hoppers - 
Draconic Evolution - 
Ender IO - 
Ender Storage 1.8+ - 
Ender Core - 
Environmental Tech - 
Exchangers - 
Extra Alchemy - 
Ectra Utilities - 
Extreme Reactors - 
FastWorkBench - 
Foamfix-0.8.3 - 
Forestry - 
FTB Utilities - 
FTBLib - 
Funky Locomotion - 
Galacticraft Planets - 
Galacticraft Core - 
Gravity Gun - 
Guide-API - 
Guidebook - 
Howling Moon - 
Ice and Fire - 
iChunUtil - 
Immersive Engineering - 
Immersive Railroading - 
Immersive Tech - 
IC2 - 
Industrial Foregoing - 
Integrated Dynamics - 
Integrated Tunnels - 
Inventory Sorter - 
Iron Backpacks - 
JEI - 
Journeymap - 
Linking through the ages - 
LLibrary - 
Mantle - 
McJtyLib - 
MCMultiPart - 
MeeCreeps - 
Mekanism + Tools + Generators - 
Mercurius - 
MmmMmmMmmMmm - 
Mob amputation - 
Mob grinding utils - 
ModTweaker - 
Morph - 
Morph-o-tool - 
Morpheus - 
MTLib - 
Mystcraft - 
MysticalLib - 
Natura - 
Not Enough Wands - 
Openblocks - 
OpenmodsLib - 
Pam's Harvestcraft - 
Placebo - 
Portal Gun - 
ProjectE - 
Psi - 
Quick Leaf Decay - 
Realm of the Dragons - 
Redstone Arsenal - 
Redstone Flux - 
Redstone Paste - 
Reliquary v1.3 - 
Resource Loader - 
RFTools + Control + Dimenstions - 
Shadowfacts' Forgelin - 
Simply Jetpacks 2 - 
Sophisticated Wolves - 
NoMoreRecipieConflict - 
Storage Drawers + Extras - 
SwingThroughGrass - 
Sync - 
Immersive Engineering - 
Tesla Core Lib - 
Thaumcraft - 
The One Probe - 
Twilight Forest - 
Thermal Cultivation + Dynamics + Expansion + Foundation + Innovation - 
Tinkers Construct - 
Tinkers' Tool Leveling - 
TiptheScapes - 
Toast control - 
TOP Addons - 
Track API - 
UniDict - 
ValkyrieLib - 
ValkyrienWarfate - 
Vampirism - 
Wanion Lib - 
Waystones - 
Wireless Crafting Terminal - 
Wolf Armor and Storage - 
WorldEdit - 
XNet - 
ZeroCore - 
</details>

I, nor anyone else on my private multiplayer server, can get the portal functionality of the portal gun to work past + or - 10,000 (give or take 20 blocks) in the X and Z directions. The gun still makes the portal shooting sound and particles appear on the target block but nothing else happens. The block/entity pick up function works fine however, regardless of distance from spawn.

**Comment by Milii20** [comment]
really fast fix, go to your server's config\portalgun.cfg, and set I:maxShootDistance from 10000 to what ever you want (i personally play with 1000000), try it, and it will work

**Comment by combustionsquirrel** [comment]
Hooray that fixed it, thanks

**Comment by iChun** [comment]
Wait, no, that sounds like a bug, not a config. I'm reopening till I get to have a look proper

**Comment by Milii20** [comment]
what ever I:maxShootDistance is used into, checks all the way from 0 0 instead of player's position

**Comment by Azutte** [comment]
Hm, I may have made my issue on the wrong repository? https://github.com/iChun/PortalGunClassic/issues/3 
![2018-11-26_23 28 01](https://user-images.githubusercontent.com/6581284/49067428-f165a300-f1d8-11e8-95aa-7ead74a6b495.png)
![2018-11-26_23 44 13](https://user-images.githubusercontent.com/6581284/49067429-f165a300-f1d8-11e8-9d0a-989068245247.png)

**Comment by iChun** [comment]
Fixed this in Portal Gun 7.1.0. Sorry for the long wait for a fix!
