### ISSUE TITLE
1.12.2 Portal gun-Invisible guns item icons and Gun

### ISSUE THREAD

**Issue by chunkedelement** [iChun/IssueTracker-Mods#155]
The item icons for the portal guns are invisible. Items can be crafted and used but are invisible. Portals still work. Disabled all texture packs and still the same results. Tried with foam fix and better fps disabled and still same results of invisible item icons and guns. Ender pearl dust and miniature black hole icons render fine, just the actual portal gun items. Also experiencing the invisible chests issue when blue portal is placed close or in same chunk with chest and yellow portal. Thanks 
ModPack: Peace of Mind version 2.0.2
MC: 1.12.2
Forge: 14.23.5.2795
PG: 7.0.2
IChun: 7.1.4
Optifine: NO
FoamFix: Yes
BetterFPS: Yes
Config changes: No
![gun enabled but invisible](https://user-images.githubusercontent.com/34798853/50038856-821fe980-fff5-11e8-8173-3ba7c24b6f78.png)
![invisible portal gun icons in jei](https://user-images.githubusercontent.com/34798853/50038857-8fd56f00-fff5-11e8-86a9-59e16fa9fa72.png)

**Comment by markismodded** [comment]
I am having the same issue.
![2018-12-16_13 37 45](https://user-images.githubusercontent.com/39780196/50058018-2f027f80-0138-11e9-8df5-ac2dd007c467.png)

**Comment by markismodded** [comment]
as you can see, it doesn't appear in portals either.
![2018-12-16_13 41 51](https://user-images.githubusercontent.com/39780196/50058030-5e18f100-0138-11e9-8b66-65968f60e6bf.png)
Nor in F5

**Comment by chunkedelement** [comment]
using < 2780 forge 1.12.2 seems to be uneffected
Build 2781:
	mezz: Implement rendering for item models with emissive quads (#5047) 
Any idea what this changes. thanks?

**Comment by chunkedelement** [comment]
using < 2780 forge 1.12.2 seems to be uneffected
Build 2781:
	mezz: Implement rendering for item models with emissive quads (#5047) 
Any idea what this changes? thanks.

**Comment by Thunder-Nova** [comment]
Might be "rendering" as 3D. Even as icons. Seems it could be a build bug. Where the 3D construct isn't taking shape. I would say rendering but that is textures mostly, not the actual 3d build.

If it where the textures, it could be application errors. Not good with mc modding, but 3D builds with SolidWorks, I had my fair share of those issues in the early days.

**Comment by ElNico56** [comment]
this happens to me too, also with gravity gun and torched

**Comment by chunkedelement** [comment]
from what ive been reading and have tested, in the forge config file change this to false and should temp fix the issue:
   B:allowEmissiveItems=false

**Comment by iChun** [comment]
Fixed this for iChunUtil 7.2.1. Thanks for letting me know about the forge change, that helped pinpoint the issue.
