### ISSUE TITLE
PortalGun Optifine Incompatibility

### ISSUE THREAD

**Issue by Traincrafter111** [iChun/IssueTracker-Mods#172]
Hi when I use PortalGun With Optifine the Portal dont render the world
![2019-09-05_09 55 31](https://user-images.githubusercontent.com/44734869/64361946-3540d080-cfd3-11e9-9a20-b449a69572a9.png)
Can you add compatibility wi Optifine please?

**Comment by iChun** [comment]
Sorry, I have no plans on adding compatibility with Optifine.
