### ISSUE TITLE
the Zoom can't cancel

### ISSUE THREAD

**Issue by foodgx** [iChun/IssueTracker-Mods#188]
It's the same to other worlds too<>

**Comment by iChun** [comment]
I have over 30 different mods. More details such as a mod name would help.

**Comment by foodgx** [comment]
「Hei Wang TANG <tangh26@dc.edu.hk>」在 2020年8月19日 週三，上午8:20 寫道：

>
>
>
>> Portal gun mod. I am not very happy with that, because I can’t play
>> minecraft with the bug. :(:(:( and it’s still happening.
>
>
>>
>>
>>

**Comment by iChun** [comment]
The zoom if I remember correctly uses the fov slider and changes the mouse
sensitivity. Unbind the zoom button and change those settings back to
normal and it should be fine.

**Comment by foodgx** [comment]
thanks!!!!!!!!!!!!!!!!!!!!!!!!!!! Because I can't play
minecraft!🙏🙏🙏🙏🙏🙏🙏 :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :)
:) :) :) :) :) :) :)
