### ISSUE TITLE
Portelgun problem

### ISSUE THREAD

**Issue by Alltimegaming** [iChun/IssueTracker-Mods#196]
Hi I downloade the mod and if I start minecraft the mod works but have no texturs all portal guns are invisible. I already search if ther are a texture pack ore someting but all what I try don´t work .

**Comment by iChun** [comment]
The mod version, MC version and source of download would be helpful
information. Unfortunately I also no longer support 1.12.2 and older so I
can only offer advice. Check your sources and make sure this isn't a result
of a mod conflict

**Comment by Alltimegaming** [comment]
ok thx it´s MC version 1.12.2
