### ISSUE TITLE
[PortalGun] 1.12.2 "See through portal" render problem [SOLVED]

### ISSUE THREAD

**Issue by defaultunknown** [iChun/IssueTracker-Mods#205]
Issue wasn't reported yet.

I guess, screenshots will tell you what's wrong.

OS: Windows 11 pro (21H2)
mode: multiplayer
modpack: FTB Sky Factory 4
logs: can't find "ForgeModLoader-server-0.log nor ForgeModLoader-client-0.log

normal:
![Screenshot (302)](https://user-images.githubusercontent.com/44570919/187085595-7830dcb8-48f8-47d6-8dd8-596e6b6ffd16.png)
first portal:
![Screenshot (303)](https://user-images.githubusercontent.com/44570919/187085596-1d8bdd56-f6d0-48f8-b20d-cd7bb55eb0db.png)
put seconds portal:
![Screenshot (304)](https://user-images.githubusercontent.com/44570919/187085597-814b94bf-1d49-4b1c-bb77-ec905a300494.png)
portal makes chests disappear with "See through portals" = Yes
![Screenshot (305)](https://user-images.githubusercontent.com/44570919/187085598-c1148feb-55d6-42bf-b68f-e50b62ddf690.png)
![Screenshot (306)](https://user-images.githubusercontent.com/44570919/187085599-6955886b-1e89-4978-8080-4160968ba50e.png)

**Comment by iChun** [comment]
Do you have any other mods like Optifine or something like that that messes around with rendering? It could also be a tile entity that doesn't like the portal render so it causes the stack to spaz out.

Unfortunately though that's the most I can offer, I don't support 1.12.2 anymore due to other obligations

**Comment by defaultunknown** [comment]
there is an "optifine 1.12.2 HD U G5"

what means "tile entity that doesn't like the portal render"?

thank you for giving advices at least :)

I will disable optifine and tell you if anything changes

UPD: Disabled optifine, no luck. Same thing.

UPD2: I also found that this bug appears only if portals are on the same side, here's a normal rendering:
![image](https://user-images.githubusercontent.com/44570919/187155052-b966d9b7-74d3-414b-9c58-19f4a16277e8.png)

**Comment by iChun** [comment]
The see through portal render is not compatible with Optifine

**Comment by defaultunknown** [comment]
I found that **optifine (Options -> Details -> Fog: OFF)** made everything as intended. Thanks, closing thread.
