### ISSUE TITLE
PiP Mod giving errors

### ISSUE THREAD

**Issue by ghost** [iChun/IssueTracker-Mods#25]
Minecraft Version: 1.8.0
Forge Version: 11.14.3.1487
Mod Version: PiP 5.0.0 iChunUtil-5.4.0
When I launch my game everything is fine until I go into my multiplayer server. I press the camera toggle button and it says "Framebuffers are not supported on your system! PiP will not work!" I have no clue what framebuffers are but there's no option to enable them. The only reason I'm posting now is because this mod was working fine until I reinstall Minecraft... I reinstalled it because it had some corrupted files. Please help! This mod is really awesome!

**Comment by iChun** [comment]
It's not giving errors. It's working as intended. According to your
settings or your graphics driver, you have Framebuffers turned off/do not
support them

**Comment by ghost** [comment]
Like I said, it was working before I reinstall minecraft. (May have been when I was screwing drivers) How do I enable this feature?

**Comment by iChun** [comment]
Check your video options, it might be there somewhere

**Comment by ghost** [comment]
In minecraft or my video driver settings?

**Comment by iChun** [comment]
MC

**Comment by ghost** [comment]
I've looked all over that, I can't find it.

**Comment by iChun** [comment]
Huh, I thought it'd be in the options. Look through your Snooper options,
there will be an opengl option like ARB/EXT_framebuffer_object or something
like that. Let me know what that is

**Comment by ghost** [comment]
I couldn't find any like that but I found a few like gl_caps[ARB_framebuffers_object] and it was set to true.

**Comment by iChun** [comment]
If those are set to true the PiP shouldn't be complaining that you disabled
Framebuffers.. Hmm. Did you update your video drivers anytime lately?

**Comment by ghost** [comment]
No, not lately.

**Comment by iChun** [comment]
how about the gl_caps[EXT_framebuffers...etc stuff? is that true or false?
I'm not really sure how else to help you out though, really sorry :/

**Comment by ghost** [comment]
It says true, all of the frame buffers I found were true. I looked top to bottom on it.

**Comment by ghost** [comment]
Well this sucks. This mod helps a lot when watching hackers. How would I enable my frame buffers in my video settings? (I have NVIDIA) I've looked all around google, nothing. Like I said before, it worked FINE before I reinstalled my minecraft. Would updating my video drivers help?

**Comment by iChun** [comment]
You could try. I'm just going off what Minecraft tells me whether if I can
use frame buffers or not so it might be something is disabling frame
buffers on minecraft.

Have you tried running just minecraft with iChunUtil and PiP?

**Comment by ghost** [comment]
The only other thing I have are InvTweaks and Optifine... Any known issues?

**Comment by iChun** [comment]
It would have been nice to know earlier that you have the god of mod
breaking mods installed. Remove it.

**Comment by ghost** [comment]
InvTweaks?

**Comment by ghost** [comment]
Removed both mods, it works! Thanks!

**Comment by fahlur** [comment]
would like to say, I disabled fast Render in optifine which fixed it for me

**Comment by CTNOriginals** [comment]
Yeah the problem was fast render in optifine for me as well, thanks to @fahlur for mentioning that.
option path: `Options > Video settings > Performance > Fast Render: (OFF->ON)`
