### ISSUE TITLE
Crash using PiP, possibly related to Galacticraft and/or Botania?

### ISSUE THREAD

**Issue by xJon** [iChun/IssueTracker-Mods#31]
Very weird. Happens after I `/pip add` someone.
http://pastebin.com/SHHgqsn4
Any idea?

**Comment by Robijnvogel** [comment]
Could you check if Galacticraft is still part of the stack trace when using the latest version(s)?

I am getting [this crash](http://pastebin.com/Mc56MX0C) when I **switch to** a view that is not a copy of my own.

**Comment by iChun** [comment]
PiP + Botania: http://pastebin.com/5hfJNMGr

**Comment by Robijnvogel** [comment]
Good to see you're looking at this :smile:

**Comment by iChun** [comment]
These are all isSneaking checks, other mods have ASMed into it but PiP is the one accidentally causing the crash. You should report it to them unless it's already been fixed, Galacticraft and Botania.
