### ISSUE TITLE
Crashing with Portal gun and Morph

### ISSUE THREAD

**Issue by Pickles256** [iChun/IssueTracker-Mods#32]
Here's the log

It happened when I went through the moon portal and after I morphed

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 11/1/15 7:03 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
    at net.minecraft.tileentity.MobSpawnerBaseLogic.func_98265_a(SourceFile:110)
    at net.minecraft.tileentity.MobSpawnerBaseLogic.func_98281_h(SourceFile:236)
    at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147517_a(SourceFile:20)
    at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147500_a(SourceFile:15)
    at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147500_a(SourceFile:10)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
    at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.tileentity.MobSpawnerBaseLogic.func_98265_a(SourceFile:110)
    at net.minecraft.tileentity.MobSpawnerBaseLogic.func_98281_h(SourceFile:236)
    at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147517_a(SourceFile:20)
    at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147500_a(SourceFile:15)
    at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147500_a(SourceFile:10)

-- Block Entity Details --
Details:
    Name: MobSpawner // net.minecraft.tileentity.TileEntityMobSpawner
    Block type: ID #52 (tile.mobSpawner // net.minecraft.block.BlockMobSpawner)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-1333,92,612), Chunk: (at 11,5,4 in -84,38; contains blocks -1344,0,608 to -1329,255,623), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,0,512 to -1025,255,1023)
    Actual block type: ID #52 (tile.mobSpawner // net.minecraft.block.BlockMobSpawner)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
    at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Pickles2566'/322, l='MpServer', x=-1338.92, y=140.41, z=610.59]]
    Chunk stats: MultiplayerChunkCache: 1089, 1089
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-248,64,224), Chunk: (at 8,4,0 in -16,14; contains blocks -256,0,224 to -241,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 45507 game time, 18655 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 146 total; [EntityZombie['Zombie'/1026, l='MpServer', x=-1342.50, y=96.00, z=555.50], EntityCreeper['Creeper'/1057, l='MpServer', x=-1358.50, y=70.00, z=562.50], EntityZombie['Zombie'/1059, l='MpServer', x=-1358.50, y=70.00, z=560.50], EntityCreeper['Creeper'/1070, l='MpServer', x=-1404.50, y=65.00, z=614.50], EntitySkeleton['Mr. Skeltal'/1072, l='MpServer', x=-1339.53, y=64.00, z=652.94], EntityZombie['Zombie'/1078, l='MpServer', x=-1353.50, y=63.00, z=580.50], EntityCreeper['Creeper'/840, l='MpServer', x=-1371.00, y=89.00, z=652.50], EntitySkeleton['Mr. Skeltal'/331, l='MpServer', x=-1326.97, y=96.00, z=622.84], EntityCreeper['Creeper'/332, l='MpServer', x=-1363.50, y=98.00, z=621.50], EntitySkeleton['Mr. Skeltal'/1100, l='MpServer', x=-1385.47, y=38.00, z=592.28], EntitySkeleton['Mr. Skeltal'/333, l='MpServer', x=-1338.88, y=126.00, z=589.50], EntitySkeleton['Mr. Skeltal'/1101, l='MpServer', x=-1384.47, y=37.00, z=589.84], EntityCreeper['Creeper'/334, l='MpServer', x=-1350.50, y=35.00, z=648.50], EntitySkeleton['Mr. Skeltal'/1102, l='MpServer', x=-1385.63, y=38.00, z=591.31], EntityBat['Bat'/335, l='MpServer', x=-1335.23, y=40.05, z=626.49], EntityBat['Bat'/336, l='MpServer', x=-1342.96, y=34.05, z=656.82], EntityBat['Bat'/337, l='MpServer', x=-1346.46, y=35.32, z=661.33], EntityBat['Bat'/338, l='MpServer', x=-1341.79, y=35.09, z=656.13], EntityBat['Bat'/339, l='MpServer', x=-1345.45, y=35.77, z=662.71], EntityBat['Bat'/340, l='MpServer', x=-1342.71, y=34.58, z=657.15], EntityCreeper['Creeper'/341, l='MpServer', x=-1351.50, y=69.00, z=654.50], EntityCreeper['Creeper'/342, l='MpServer', x=-1335.50, y=88.00, z=638.00], EntitySkeleton['Mr. Skeltal'/343, l='MpServer', x=-1368.06, y=27.00, z=632.53], EntityZombie['Zombie'/344, l='MpServer', x=-1357.50, y=69.00, z=591.50], EntityZombie['Zombie'/345, l='MpServer', x=-1312.50, y=22.00, z=585.50], EntityPig['Pig'/346, l='MpServer', x=-1319.50, y=126.00, z=577.50], EntityPig['Pig'/347, l='MpServer', x=-1329.97, y=126.00, z=571.03], EntitySpider['Spider'/348, l='MpServer', x=-1315.72, y=142.00, z=595.97], EntityBat['Bat'/349, l='MpServer', x=-1314.75, y=36.09, z=572.30], EntityBat['Bat'/350, l='MpServer', x=-1306.39, y=42.46, z=598.09], EntityBat['Bat'/351, l='MpServer', x=-1306.22, y=43.91, z=590.27], EntitySkeleton['Mr. Skeltal'/352, l='MpServer', x=-1308.50, y=42.00, z=599.50], EntityZombie['Zombie'/353, l='MpServer', x=-1308.00, y=42.00, z=587.56], EntityPig['Pig'/354, l='MpServer', x=-1307.97, y=102.00, z=612.03], EntityBat['Bat'/866, l='MpServer', x=-1309.87, y=50.07, z=570.94], EntityPig['Pig'/355, l='MpServer', x=-1309.41, y=103.00, z=605.38], EntityPig['Pig'/356, l='MpServer', x=-1304.50, y=112.00, z=601.47], EntityPig['Pig'/357, l='MpServer', x=-1306.97, y=130.00, z=600.47], EntityCreeper['Creeper'/358, l='MpServer', x=-1319.50, y=77.00, z=647.50], EntityBat['Bat'/359, l='MpServer', x=-1304.72, y=44.10, z=598.63], EntityCow['Cow'/360, l='MpServer', x=-1296.47, y=91.00, z=647.28], EntityCow['Cow'/361, l='MpServer', x=-1294.25, y=94.00, z=643.38], EntityBat['Bat'/362, l='MpServer', x=-1349.42, y=33.86, z=654.35], EntityTrail['unknown'/874, l='MpServer', x=-1338.92, y=140.62, z=610.59], EntitySquid['Squid'/363, l='MpServer', x=-1387.59, y=54.53, z=594.50], EntityZombie['Zombie'/364, l='MpServer', x=-1385.50, y=99.00, z=603.50], EntityZombie['Zombie'/365, l='MpServer', x=-1392.06, y=98.00, z=604.47], EntitySkeleton['Mr. Skeltal'/366, l='MpServer', x=-1346.50, y=29.00, z=561.50], EntityCreeper['Creeper'/1134, l='MpServer', x=-1324.50, y=74.00, z=683.50], EntityZombie['Zombie'/367, l='MpServer', x=-1347.50, y=75.00, z=571.50], EntityCreeper['Creeper'/879, l='MpServer', x=-1332.72, y=65.00, z=547.13], EntityPig['Pig'/368, l='MpServer', x=-1318.47, y=125.00, z=575.53], EntityPig['Pig'/369, l='MpServer', x=-1323.53, y=125.00, z=577.53], EntityPig['Pig'/370, l='MpServer', x=-1320.66, y=73.00, z=667.91], EntityPig['Pig'/371, l='MpServer', x=-1319.19, y=75.00, z=670.47], EntityPig['Pig'/372, l='MpServer', x=-1321.25, y=74.00, z=669.38], EntitySquid['Squid'/373, l='MpServer', x=-1385.59, y=56.34, z=640.53], EntitySquid['Squid'/374, l='MpServer', x=-1381.19, y=52.88, z=580.63], EntitySquid['Squid'/375, l='MpServer', x=-1377.78, y=54.75, z=580.81], EntitySquid['Squid'/376, l='MpServer', x=-1386.88, y=55.31, z=580.22], EntitySquid['Squid'/377, l='MpServer', x=-1384.38, y=55.34, z=577.22], EntitySquid['Squid'/378, l='MpServer', x=-1390.41, y=55.28, z=580.69], EntitySquid['Squid'/379, l='MpServer', x=-1382.66, y=53.09, z=584.09], EntitySquid['Squid'/380, l='MpServer', x=-1383.91, y=54.00, z=586.06], EntityBat['Bat'/892, l='MpServer', x=-1365.25, y=27.00, z=632.75], EntitySquid['Squid'/381, l='MpServer', x=-1383.75, y=55.31, z=588.31], EntitySquid['Squid'/382, l='MpServer', x=-1385.31, y=55.06, z=588.19], EntityBat['Bat'/894, l='MpServer', x=-1373.18, y=25.36, z=624.42], EntitySquid['Squid'/383, l='MpServer', x=-1389.81, y=54.56, z=591.22], EntitySheep['Sheep'/384, l='MpServer', x=-1305.59, y=81.00, z=562.59], EntitySheep['Sheep'/385, l='MpServer', x=-1307.53, y=82.00, z=564.53], EntitySheep['Sheep'/386, l='MpServer', x=-1307.50, y=84.00, z=562.34], EntitySheep['Sheep'/387, l='MpServer', x=-1307.53, y=82.00, z=564.53], EntityCreeper['Creeper'/388, l='MpServer', x=-1284.50, y=79.00, z=651.50], EntityCow['Cow'/389, l='MpServer', x=-1293.50, y=94.00, z=645.50], EntityCow['Cow'/390, l='MpServer', x=-1292.22, y=93.00, z=649.47], EntityZombie['Zombie'/391, l='MpServer', x=-1288.50, y=85.00, z=646.50], EntityPig['Pig'/392, l='MpServer', x=-1284.50, y=123.00, z=648.50], EntityPig['Pig'/393, l='MpServer', x=-1285.50, y=119.00, z=649.50], EntityPig['Pig'/394, l='MpServer', x=-1282.50, y=125.00, z=651.50], EntityPig['Pig'/395, l='MpServer', x=-1286.78, y=125.00, z=644.56], EntitySkeleton['Mr. Skeltal'/396, l='MpServer', x=-1311.50, y=70.00, z=667.50], EntityEnderman['Enderman'/397, l='MpServer', x=-1333.16, y=119.00, z=558.97], EntityPig['Pig'/398, l='MpServer', x=-1268.50, y=82.00, z=614.50], EntityPig['Pig'/399, l='MpServer', x=-1268.50, y=82.00, z=614.50], EntityPig['Pig'/401, l='MpServer', x=-1316.31, y=127.00, z=553.50], EntityPig['Pig'/402, l='MpServer', x=-1326.50, y=120.00, z=549.19], EntityPig['Pig'/403, l='MpServer', x=-1321.47, y=124.00, z=550.19], EntitySkeleton['Mr. Skeltal'/404, l='MpServer', x=-1265.50, y=95.00, z=631.50], EntityBat['Bat'/405, l='MpServer', x=-1315.57, y=49.83, z=691.84], EntityPig['Pig'/407, l='MpServer', x=-1323.50, y=75.00, z=672.88], EntitySkeleton['Mr. Skeltal'/408, l='MpServer', x=-1321.50, y=76.00, z=672.50], EntityCreeper['Creeper'/409, l='MpServer', x=-1361.50, y=41.00, z=687.50], EntitySkeleton['Mr. Skeltal'/410, l='MpServer', x=-1360.50, y=41.00, z=687.50], EntityCreeper['Creeper'/1178, l='MpServer', x=-1290.25, y=45.00, z=589.88], EntitySquid['Squid'/411, l='MpServer', x=-1398.56, y=52.16, z=651.78], EntitySquid['Squid'/412, l='MpServer', x=-1399.91, y=56.38, z=637.88], EntitySquid['Squid'/413, l='MpServer', x=-1401.72, y=56.31, z=638.88], EntitySquid['Squid'/414, l='MpServer', x=-1395.50, y=54.34, z=642.97], EntitySquid['Squid'/415, l='MpServer', x=-1400.31, y=56.28, z=654.44], EntitySquid['Squid'/416, l='MpServer', x=-1394.19, y=55.34, z=643.81], EntitySkeleton['Mr. Skeltal'/928, l='MpServer', x=-1280.50, y=118.00, z=639.50], EntitySquid['Squid'/417, l='MpServer', x=-1401.47, y=54.09, z=642.72], EntitySquid['Squid'/418, l='MpServer', x=-1398.47, y=54.41, z=644.06], EntitySquid['Squid'/419, l='MpServer', x=-1396.81, y=54.25, z=647.69], EntitySquid['Squid'/420, l='MpServer', x=-1393.00, y=55.97, z=653.00], EntityPig['Pig'/421, l='MpServer', x=-1297.84, y=65.00, z=670.03], EntitySquid['Squid'/422, l='MpServer', x=-1403.13, y=58.94, z=663.56], EntitySquid['Squid'/423, l='MpServer', x=-1396.06, y=60.78, z=660.75], EntitySquid['Squid'/426, l='MpServer', x=-1402.50, y=60.19, z=669.97], EntityZombie['Zombie'/682, l='MpServer', x=-1345.50, y=91.00, z=571.50], EntitySquid['Squid'/427, l='MpServer', x=-1394.50, y=61.13, z=665.38], EntitySquid['Squid'/428, l='MpServer', x=-1397.97, y=61.25, z=673.38], EntitySquid['Squid'/432, l='MpServer', x=-1401.44, y=52.38, z=564.16], EntityCreeper['Creeper'/945, l='MpServer', x=-1264.50, y=106.00, z=673.50], EntitySquid['Squid'/433, l='MpServer', x=-1399.72, y=49.94, z=570.41], EntitySquid['Squid'/434, l='MpServer', x=-1404.47, y=48.19, z=561.88], EntitySquid['Squid'/438, l='MpServer', x=-1400.78, y=52.41, z=565.53], EntityCreeper['Creeper'/950, l='MpServer', x=-1330.44, y=114.00, z=539.00], EntityZombie['Zombie'/439, l='MpServer', x=-1279.50, y=55.00, z=574.50], EntityPig['Pig'/440, l='MpServer', x=-1262.03, y=81.00, z=609.50], EntityPig['Pig'/441, l='MpServer', x=-1286.50, y=71.00, z=684.22], EntitySkeleton['Mr. Skeltal'/442, l='MpServer', x=-1293.50, y=64.00, z=684.50], EntitySpider['Spider'/954, l='MpServer', x=-1355.56, y=34.25, z=649.81], EntityCreeper['Creeper'/443, l='MpServer', x=-1275.47, y=66.00, z=679.69], EntitySpider['Spider'/444, l='MpServer', x=-1283.41, y=63.05, z=681.00], EntityCreeper['Creeper'/956, l='MpServer', x=-1278.94, y=126.00, z=596.38], EntitySpider['Spider'/445, l='MpServer', x=-1282.19, y=64.00, z=682.88], EntitySpider['Spider'/1214, l='MpServer', x=-1278.50, y=52.00, z=557.50], EntityCreeper['Creeper'/960, l='MpServer', x=-1302.50, y=81.00, z=639.50], EntitySkeleton['Mr. Skeltal'/1216, l='MpServer', x=-1274.50, y=52.00, z=560.50], EntityCreeper['Creeper'/961, l='MpServer', x=-1300.50, y=81.00, z=639.50], EntityPig['Pig'/451, l='MpServer', x=-1325.47, y=119.00, z=543.53], EntityCreeper['Creeper'/964, l='MpServer', x=-1352.50, y=76.00, z=536.50], EntityZombie['Zombie'/453, l='MpServer', x=-1369.50, y=48.00, z=541.50], EntityBat['Bat'/454, l='MpServer', x=-1286.75, y=50.71, z=541.78], EntitySkeleton['Mr. Skeltal'/976, l='MpServer', x=-1345.50, y=41.00, z=580.50], EntityCreeper['Creeper'/479, l='MpServer', x=-1266.50, y=137.00, z=543.50], EntityZombie['Zombie'/991, l='MpServer', x=-1344.50, y=37.00, z=679.50], EntityPig['Pig'/481, l='MpServer', x=-1260.72, y=73.00, z=685.47], EntitySkeleton['Mr. Skeltal'/993, l='MpServer', x=-1319.88, y=113.00, z=610.50], EntityPig['Pig'/482, l='MpServer', x=-1265.50, y=65.00, z=688.31], EntityZombie['Zombie'/1003, l='MpServer', x=-1376.50, y=79.00, z=555.50], EntityCreeper['Creeper'/1011, l='MpServer', x=-1314.50, y=71.00, z=685.50], EntityArrow['Doot Doot'/1269, l='MpServer', x=-1442.59, y=112.52, z=606.80], EntityClientPlayerMP['Pickles2566'/322, l='MpServer', x=-1338.92, y=140.41, z=610.59]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 410298672 bytes (391 MB) / 914509824 bytes (872 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 25 mods loaded, 25 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1481-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1481} [Minecraft Forge](forge-1.7.10-10.13.4.1481-1.7.10.jar) 
    UCHIJAAAA   RenderPlayerAPI{1.0} [Render Player API](minecraft.jar) 
    UCHIJAAAA   TooManyItems{1.7.10} [TooManyItems](minecraft.jar) 
    UCHIJAAAA   AIRI{3.0.0-1.7.10} [AIRI]([1.7.10-10.13.0.1158][3.0.2-1.7.10] AIRI.jar) 
    UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAAAA   BiblioCraft{1.10.4} [BiblioCraft](BiblioCraft[v1.10.4][MC1.7.10].jar) 
    UCHIJAAAA   CosmeticArmor{1.0.5} [Cosmetic Armor](CosmeticArmor-1.7.10-1.0.5.B8-universal.jar) 
    UCHIJAAAA   customnpcs{1.7.10d} [CustomNpcs](CustomNPCs_1.7.10d.jar) 
    UCHIJAAAA   flansmod{4.10.0} [Flan's Mod](Flans Mod-1.7.10-4.10.0.jar) 
    UCHIJAAAA   GollumCoreLib{2.0.0} [Gollum Core Lib](GollumCoreLib-2.0.0Beta1.0-1.7.10.jar) 
    UCHIJAAAA   iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCHIJAAAA   ForgeMultipart{1.1.2.331} [Forge Multipart](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCHIJAAAA   Mekanism{8.1.6} [Mekanism](Mekanism-1.7.10-8.1.6.249.jar) 
    UCHIJAAAA   testdummy{1.0} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.6.jar) 
    UCHIJAAAA   MorePistons{2.0.0 Beta 1.0} [More Pistons](MorePistons-2.0.0Beta1.0-1.7.10.jar) 
    UCHIJAAAA   Morph{0.9.0} [Morph](Morph-Beta-0.9.0.jar) 
    UCHIJAAAA   cfm{3.4.7} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.7%281.7.10%29.jar) 
    UCHIJAAAA   PortalGun{4.0.0-beta} [PortalGun](PortalGun-4.0.0-beta.jar) 
    UCHIJAAAA   HeroSuits{1.2} [Project Superhuman](ProjectSuperhuman - v1.2 - 1.7.10.jar) 
    UCHIJAAAA   RedstonePasteMod{1.6.2} [Redstone Paste](RedstonePasteMod-1.7.10-1.6.2.jar) 
    UCHIJAAAA   ReiMinimap{1.7.10} [Rei's Minimap](Reis-Minimap-Mod-1.7.10.jar) 
    UCHIJAAAA   McMultipart{1.1.2.331} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCHIJAAAA   ForgeMicroblock{1.1.2.331} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.0' Renderer: 'AMD Radeon HD 5700 Series'
    Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 5700 Series GL version 4.5.13399 Compatibility Profile Context 15.201.1151.0, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [HRF_RP_1.6.2_x64.zip, thank mr skeltal 1.7 1.8.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by iChun** [comment]
It's neither of those mods. The log doesn't point to anything non-minecraft
but it could be caused by a mod that adds mob spawners, which morph and
Portal gun do not.

**Comment by Pickles256** [comment]
Hey I changed it to be just morph and portal but it still crashes?

**Comment by iChun** [comment]
Can you get me the log with just those two mods instead?

**Comment by Pickles256** [comment]
Apparently the world got corrupted and that was the problem

Sorry to bother you I love your work!
