### ISSUE TITLE
[PortalGun] Chunkloaded chunk error

### ISSUE THREAD

**Issue by vsilvar** [iChun/IssueTracker-Mods#36]
When trying to use a PortalGun in a claimed chunkloaded chunk (with FTBUtilities), the following happens, kicking the player from the server:
http://pastebin.com/cj3vbVQs

Server: Linux x64 SMP
PortalGun: 4.0.0-beta-6
FTBUtilities: 1.0.13
Forge: 10.13.4.1614

**Comment by iChun** [comment]
Not sure if this is still an issue with the new PG which also chunkloads cause it looks like back then it was an issue with two different chunk reference classes. Hopefully no longer an issue now.
