### ISSUE TITLE
[1.9] 1.9.0v1 crashes dedicated forge server 1.9 build 1809 on startup

### ISSUE THREAD

**Issue by kreezxil** [iChun/IssueTracker-Mods#37]
Issue: DeathCounter{MC1.9.0v1} crashes dedicated forge server 1.9 build 1809 on startup

crash report:
https://gist.github.com/0dc9e955e341a28468e8

fml server latest:
https://gist.github.com/99c535a85f9933459973

**Comment by iChun** [comment]
Been sorted, a couple of mods have already been updated to fix this.
