### ISSUE TITLE
[Gravity Gun] ae2 drops drives and copies them.

### ISSUE THREAD

**Issue by ParkerMc** [iChun/IssueTracker-Mods#41]
This was on troll craft I have not had time to confirm on my system it I will do that soon. But anyway when you pick up the Me drive  drops the drive items then they still show up with all the drives. Could be if you are destorying the block, just replaceing it with air should fix it.
https://youtu.be/HmToAch3kFw?t=13m30s

**Comment by iChun** [comment]
Is this still an issue in 1.10.2+?

**Comment by ParkerMc** [comment]
I don't know let me test and get back to you.

**Comment by ParkerMc** [comment]
Now it just crashes for me. If it matters I could only get it to pickup 
with the super charged one.

Crash log: https://gist.github.com/ParkerMc/981f02a63a14a6c573b2cb91696015be

**Comment by iChun** [comment]
Oh, um, this probably needs to be brought to AE's attention.

Also FYI you can't pick up tile entities with the normal gravity gun
anymore (configurable). This is to make the supercharged version feel more
worth it.

**Comment by ParkerMc** [comment]
Ok got it thanks for your time.
