### ISSUE TITLE
[1.10.2] Gravity Gun crash with Waila/Wawla

### ISSUE THREAD

**Issue by GirafiStudios** [iChun/IssueTracker-Mods#42]
Picking up a block with a gravity gun, seem to cause the attached crash log. (9/10 times)

Crash log: https://gist.github.com/GirafiStudios/c04560a91c1060ddfdae3e83fffe35d2

**Comment by iChun** [comment]
Fixed. Will be hotfixed on Curse and my site in a few minutes. https://github.com/iChun/iChunUtil/commit/6072a2aea06e5fd26efb699a25fa802cad4ae1a7

**Comment by GirafiStudios** [comment]
Thanks for the quick fix!

This seem to have introduced a new issue though.
When picking up a block with the gravity gun, it doesn't seem to render the block in entity form anymore.

**Comment by iChun** [comment]
Confirmed. I should have tested this first lmao. I'll pop up a fix later
today and a new build. Thanks Girafi

**Comment by iChun** [comment]
Hotfix 2 is up
