### ISSUE TITLE
back tools mod disfunctional

### ISSUE THREAD

**Issue by ghost** [iChun/IssueTracker-Mods#43]
I'm using shaders, mo bends, primalcore and the survivalist mod. The tools when switching in the hotbar simply do not appear on the back.

**Comment by iChun** [comment]
Does it work without the other mods installed? Particularly the shaders mod.

**Comment by ghost** [comment]
@iChun Confirmed, its a bug with Mo'bends mod.

**Comment by iChun** [comment]
Thanks. Isn't this the mod that adds joints to the models or something?
They need to copy over the layer renderer if they're gonna change the
renderer. Might not be 100% compatible though.

**Comment by ghost** [comment]
@iChun Do I need to report this over there then?

**Comment by iChun** [comment]
Yeah, there's nothing I can really do on my end.

**Comment by iChun** [comment]
Well, there is, but the way I'm doing it is already done to increase
compatibility with mods that replace renderers and something still broke :S
