### ISSUE TITLE
[Immersive Engineering 57][Back Tools 1.10.2-6.0.0] Nondescript Compatibility Issue Report

### ISSUE THREAD

**Issue by Alaberti** [iChun/IssueTracker-Mods#44]
"Railgun" ![2017-03-22_11 58 44](https://cloud.githubusercontent.com/assets/10929796/24210494/514d0d6a-0ef7-11e7-8b84-a1fe049539e0.png) 

"Revolver" ![2017-03-22_12 02 56](https://cloud.githubusercontent.com/assets/10929796/24210562/8727ddd4-0ef7-11e7-83b6-59b9f29be62c.png) 

"Chem Thrower" ![2017-03-22_12 03 30](https://cloud.githubusercontent.com/assets/10929796/24210583/93f16d50-0ef7-11e7-8902-0a2ae3e035f8.png) 

@blusunrize I love your models more every time I see them

Edit: I think the pictures speak for themselves - using Back Tools with Immersive Engineering weapons causes...that.

**Comment by BluSunrize** [comment]
That's a hilariously nondescript issue report.
Makes me feel bad for iChun...

**Comment by iChun** [comment]
Well @BluSunrize, GO ON.

**Comment by Alaberti** [comment]
Fixed it~

**Comment by iChun** [comment]
Oh right this was back tools. I thought it was an iChunUtil issue and was really confused for a bit. What was the fix?

**Comment by BluSunrize** [comment]
Don't think there is one. The "Fixed it" referred to the fixed title. I'm assuming you're expected to fix this, iChun, so have fun. =P

**Comment by iChun** [comment]
I need to see how you do your rendering for the model. Mind dropping me a
linkie?

**Comment by BluSunrize** [comment]
good luck. My custom OBJ BakedModels are a mess (but only because OBJ in Forge is utter garbage)

https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/client/models/IESmartObjModel.java

**Comment by Alaberti** [comment]
Has there been any success in addressing this issue? Thank you for your time.

**Comment by BluSunrize** [comment]
I didn't do anything on it.

**Comment by iChun** [comment]
Not yet. My main intention for the update to 1.12.2 was go get all my mods
to 1.12.2 first and then I'll work on  bug fixes.

**Comment by Alaberti** [comment]
Hello. Just a routine bi-annual progress check.
