### ISSUE TITLE
[1.10.2] Gravity Gun localization issues

### ISSUE THREAD

**Issue by GirafiStudios** [iChun/IssueTracker-Mods#45]
It seems that everything that is supposes to be localized isn't. At least item names & the config

Examples:
![806f586c569c498ca71c708468e51756](https://cloud.githubusercontent.com/assets/6305377/24409207/d5943daa-13cf-11e7-91a4-762667caecb5.png)
![cf329185e11445c38367e1fd93094f01](https://cloud.githubusercontent.com/assets/6305377/24409215/d98befb6-13cf-11e7-876b-73dc9785f4a9.png)

Gravity Gun version:  6.0.0
iChunUtil verison: 6.2.0 (Hotfix 2)
Minecraft Forge version. 12.18.3.2254
No other mods installed.

**Comment by iChun** [comment]
I forgot to fix this. :(

**Comment by GirafiStudios** [comment]
No worries, it is not that big a deal!
Just opened an issue as a friendly reminder ^^ Take your time!

**Comment by GirafiStudios** [comment]
Fixed in the 1.12.2 version of Gravity Gun, so closing this!

**Comment by iChun** [comment]
I maaaaay have forgotten about this issue report though I did fix it in all
the mods I released today.... I think.
