### ISSUE TITLE
[1.10.2][PortalGun] Crash when creating a second portal

### ISSUE THREAD

**Issue by ToadsworthLP** [iChun/IssueTracker-Mods#47]
When creating the first portal, anything works fine, but as soon as I try to create a second one so I can travel between them, the game crashes the server. Here's the crash report: https://pastebin.com/g8XSgGCN
Happened in 4 out of 4 tries

**Comment by iChun** [comment]
Is this a crash on the server or the client?

**Comment by ToadsworthLP** [comment]
The server crashes, the client just logs out without crashing. However, I didn't test if the client crashes too if you do it in a singleplayer world.

**Comment by Desempregago** [comment]
I'm also having this on my client, but the game doesn't close automatically, only freezes.
Viewing the crash log, this shows up:

java.lang.NoSuchFieldError: field_189564_r
	at me.ichun.mods.ichunutil.common.module.worldportals.client.render.world.chunk.RenderChunkWorldPortal.func_178581_b(RenderChunkWorldPortal.java:69)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Unknown Source)

**Comment by Desempregago** [comment]
Has something to do with the portal world rendering, I think.

**Comment by ToadsworthLP** [comment]
My issue is a bit different since it misses the class org/lwjgl/util/vector/Matrix4f , but it seems "mine" gets triggered by the rendering too.

**Comment by 63502** [comment]
When I have the special looking through the portal render enabled, I get the above client crash too.
[Crash Log](https://gist.github.com/63502/9b8bd3ccc858a27a85932d8a0b21fc06)

Without the special render enabled, both portals place down and function just fine, but with the looking through portal render enabled, the game crashes on placing the second portal.

I should also mention that the edge of the non special rendered portal is a bit choppy looking. It may need a minor cosmetic touch up.
![2017-04-11_20 57 20](https://cloud.githubusercontent.com/assets/15267053/24937172/c913c856-1efc-11e7-9e14-3fb7717b0123.png)

**Comment by Desempregago** [comment]
Are you using OptiFine? I think it might have something to do with the rendering, I'll try again without it.

**Comment by a-frenzy** [comment]
I'm getting this same issue looks like https://gist.github.com/frenzye/1e31dec687935d4d68d77fa92edc8c88

**Comment by iChun** [comment]
Fixed iChunUtil 6.3.1. https://github.com/iChun/iChunUtil/commit/148b79a877736103437fb4ca90a0a6034259f6c5
