### ISSUE TITLE
[1.10.2] [Portal Gun] Ender Pearl Dust lang needs to be updated

### ISSUE THREAD

**Issue by ThomasAunvik** [iChun/IssueTracker-Mods#50]
Ender Pearl Dust does not have it registered itself on the lang file.
The name of the Ender Pearl Dust in minecraft is:
`item.portalgun.item.dustenderpearl.name`

But in the en_US.lang file it is:
`item.portalgun.item.dustEnderPearl.name=Ender Pearl Dust`

This issue can easily be fixed.

**Comment by iChun** [comment]
Fixed for PG 6.0.1.
