### ISSUE TITLE
[1.10.2] [Portal Gun] Portal Gun (Newly Crafted Portal Gun) does not work

### ISSUE THREAD

**Issue by ThomasAunvik** [iChun/IssueTracker-Mods#51]
After crafting a Portal Gun (Newly Crafted Portal Gun), the portal gun does not work at all.

When holding the portal gun:
![Imgur](http://i.imgur.com/TwKo8ia.png)

**Comment by AndyBTTF** [comment]
That seemed to only happen when I grabbed it via command. When I manually crafted it, it worked fine.

**Comment by iChun** [comment]
This has been fixed (for the most part) for PG 6.0.1
