### ISSUE TITLE
[1.10.2] [Portal Gun] portal moves when in F5 mode

### ISSUE THREAD

**Issue by vos6434** [iChun/IssueTracker-Mods#54]
[https://i.gyazo.com/cd39025867620255e25b7886eecb5246.gif](url)

**Comment by ThomasAunvik** [comment]
Hyperlink is broken.

Also, seems it is confirmed as it also happens to me too.

**Comment by iChun** [comment]
Relinking: https://i.gyazo.com/cd39025867620255e25b7886eecb5246.gif

That's... a really weird one.

**Comment by iChun** [comment]
Only in reverse facing third person cam. Gotcha.

**Comment by iChun** [comment]
Fixed in a ridiculously absurd manner that makes no sense to anyone. Slated for PG 6.0.1 release.
