### ISSUE TITLE
Unable to turn of Portal Shaders

### ISSUE THREAD

**Issue by Biomedef** [iChun/IssueTracker-Mods#55]
I am not able to turn off the fancy portals.
If i set them to "no" and click "Done" it sets them back to true.

**Comment by ThomasAunvik** [comment]
Try doing it manually in the config folder.

**Comment by iChun** [comment]
That won't work. I know why this is happening already, some debug code left
over.

**Comment by Biomedef** [comment]
it is not working turning it off manually eighter.
it's just turning it back on.

**Comment by iChun** [comment]
Fixed for PG 6.0.1
