### ISSUE TITLE
PortalGun: One Green Portal

### ISSUE THREAD

**Issue by alktat** [iChun/IssueTracker-Mods#57]
Using any portal gun yields the results of having one portal entirely green and the other perfectly fine. Even with mods, the event still occurs. Optifine is not installed. The link to a screenshot taken of the event is [here](http://imgur.com/5yWRgul).

My "specs" of my computer is [here](http://imgur.com/rMwxmAb).

**Comment by iChun** [comment]
There is a fix that I implemented for PG 6.0.1 regarding the shaders. Can you try that out (when released) and let me know if this is still an issue?

**Comment by iChun** [comment]
PG 6.0.1 is now out. I'm gonna close this in the meantime but please do let me know if the green portals are fixed.
