### ISSUE TITLE
(OPTIFINE ISSUE) Game Crash "Description: Batching chunks"

### ISSUE THREAD

**Issue by Peekofwar** [iChun/IssueTracker-Mods#61]
So, I place two portals.,. them my game crashed. I deleted a mod that required me to specify my memory allocation, then launched the game and loaded my world. The world was rendering and I looked up at the portals. It looked like space in them and my game crashed,

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.10.2-4.2.10.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 4/13/17 8:25 PM
Description: Batching chunks

java.lang.NoSuchFieldError: field_189564_r
	at me.ichun.mods.ichunutil.common.module.worldportals.client.render.world.chunk.RenderChunkWorldPortal.func_178581_b(RenderChunkWorldPortal.java:69)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Peekofwar'/1547, l='MpServer', x=-353.03, y=70.00, z=-497.23]]
	Chunk stats: MultiplayerChunkCache: 164, 164
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (96,64,-140), Chunk: (at 0,4,4 in 6,-9; contains blocks 96,0,-144 to 111,255,-129), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 2647870 game time, 17367 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 42 total; [EntitySheep['Sheep'/1669, l='MpServer', x=-343.65, y=64.00, z=-565.21], MoCEntityFirefly['Firefly'/1670, l='MpServer', x=-349.23, y=64.00, z=-564.32], MoCEntityHorse['WildHorse'/1671, l='MpServer', x=-366.69, y=70.00, z=-492.86], MoCEntityHorse['WildHorse'/1672, l='MpServer', x=-366.72, y=70.00, z=-486.82], EntityLatchedRenderer['unknown'/1992, l='MpServer', x=-353.03, y=70.00, z=-497.23], MoCEntityHorse['WildHorse'/1673, l='MpServer', x=-361.01, y=70.00, z=-494.07], EntitySheep['Sheep'/1674, l='MpServer', x=-378.64, y=67.00, z=-561.23], MoCEntityHorse['WildHorse'/1548, l='MpServer', x=-366.66, y=70.00, z=-499.11], MoCEntityHorse['WildHorse'/1549, l='MpServer', x=-358.94, y=70.00, z=-497.59], MoCEntitySalmon['Salmon'/1614, l='MpServer', x=-333.70, y=62.00, z=-564.68], MoCEntityAngelFish['AngelFish'/1619, l='MpServer', x=-313.85, y=62.00, z=-546.57], MoCEntityWyvern['Wyvern'/1685, l='MpServer', x=-354.75, y=69.00, z=-454.08], EntitySheep['Sheep'/1623, l='MpServer', x=-394.66, y=71.00, z=-472.24], MoCEntityTurkey['Turkey'/1624, l='MpServer', x=-397.72, y=72.00, z=-473.56], MoCEntitySnail['Snail'/1625, l='MpServer', x=-287.31, y=70.00, z=-479.69], EntityPig['Pig'/1626, l='MpServer', x=-278.54, y=69.00, z=-465.26], EntityItem['item.tile.spruceFenceGate'/1694, l='MpServer', x=-345.63, y=70.00, z=-498.29], EntityItem['item.item.verticalHatch'/1695, l='MpServer', x=-346.46, y=70.00, z=-499.06], MoCEntityBee['Bee'/1701, l='MpServer', x=-393.90, y=43.00, z=-460.39], EntitySheep['Sheep'/1638, l='MpServer', x=-357.73, y=64.00, z=-553.77], MoCEntityAnt['Ant'/1702, l='MpServer', x=-393.46, y=65.00, z=-450.53], EntitySheep['Sheep'/1704, l='MpServer', x=-422.55, y=61.97, z=-514.48], EntitySheep['Sheep'/1705, l='MpServer', x=-426.28, y=62.04, z=-512.81], EntitySheep['Sheep'/1642, l='MpServer', x=-385.48, y=72.24, z=-494.45], MoCEntityHorse['WildHorse'/1706, l='MpServer', x=-422.65, y=62.59, z=-527.20], EntitySheep['Sheep'/1643, l='MpServer', x=-385.21, y=74.00, z=-492.17], EntitySheep['Sheep'/1710, l='MpServer', x=-289.76, y=71.00, z=-480.52], MoCEntitySalmon['Salmon'/1646, l='MpServer', x=-298.30, y=61.00, z=-549.19], EntityPlayerSP['Peekofwar'/1547, l='MpServer', x=-353.03, y=70.00, z=-497.23], EntityTameableDragon['Aether Dragon'/1650, l='MpServer', x=-353.45, y=70.00, z=-513.38], EntityTameableDragon['Ghost Dragon'/1651, l='MpServer', x=-353.81, y=70.00, z=-514.80], MoCEntitySalmon['Salmon'/1715, l='MpServer', x=-307.30, y=62.00, z=-522.30], MoCEntityRaccoon['Raccoon'/1716, l='MpServer', x=-310.35, y=62.77, z=-523.14], EntitySheep['Sheep'/1654, l='MpServer', x=-396.16, y=70.00, z=-570.81], EntityPig['Pig'/1659, l='MpServer', x=-372.49, y=68.00, z=-450.59], EntitySheep['Sheep'/1724, l='MpServer', x=-373.77, y=66.00, z=-552.78], EntityLatchedRenderer['unknown'/1597, l='MpServer', x=8.50, y=65.00, z=8.50], EntitySheep['Sheep'/1725, l='MpServer', x=-376.56, y=67.00, z=-546.26], MoCEntityFirefly['Firefly'/1598, l='MpServer', x=-408.74, y=74.00, z=-502.71], MoCEntityScorpion['Scorpion'/1982, l='MpServer', x=-427.50, y=77.00, z=-503.50], EntityPig['Pig'/1726, l='MpServer', x=-286.66, y=72.00, z=-513.25], MoCEntityAnt['Ant'/1727, l='MpServer', x=-287.01, y=72.00, z=-516.15]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/1597, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:57)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 502431520 bytes (479 MB) / 1971322880 bytes (1880 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 102
	FML: MCP 9.32 Powered by Forge 12.18.3.2221 Optifine OptiFine_1.10.2_HD_U_D4 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2221.jar) 
	UCHIJAAAA	Forge{12.18.3.2221} [Minecraft Forge] (forge-1.10.2-12.18.3.2221.jar) 
	UCHIJAAAA	animalbikes{1.10.2} [Animal Bikes] (AnimalBikes_1.10.2(19nov16).jar) 
	UCHIJAAAA	customspawner{3.10.1} [DrZhark's CustomSpawner] (CustomMobSpawner 3.10.1.jar) 
	UCHIJAAAA	customnpcs{1.10.2_beta} [CustomNPCs] (CustomNPCs_1.10.2_beta(30oct16).jar) 
	UCHIJAAAA	DragonMounts{r46-1.10.2} [Dragon Mounts] (DragonMounts-r46-1.10.2.jar) 
	UCHIJAAAA	mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod-10.0.6.jar) 
	UCHIJAAAA	ichunutil{6.3.0} [iChunUtil] (iChunUtil-1.10.2-6.3.0.jar) 
	UCHIJAAAA	malisiscore{1.10.2-4.2.10} [MalisisCore] (malisiscore-1.10.2-4.2.10.jar) 
	UCHIJAAAA	malisisdoors{1.10.2-5.1.8} [MalisisDoors] (malisisdoors-1.10.2-5.1.8.jar) 
	UCHIJAAAA	moreplayermodels{1.10.2} [MorePlayerModels] (MorePlayerModels_1.10.2(30oct16).jar) 
	UCHIJAAAA	portalgun{6.0.0} [PortalGun] (PortalGun-1.10.2-6.0.0.jar) 
	UCHIJAAAA	thutcore{3.6.5} [ThutCore] (thutcore-1.9.4-3.6.5.3.jar) 
	UCHIJAAAA	thuttech{4.0.5} [Thut's Tech] (thuttech-4.0.5.jar) 
	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.10.2-4.2.10.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2221
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: invisable_saddle.zip (incompatible), custome_pack_v1.5.0_01.zip (incompatible), Dragon Mount Aetheric Retexture
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-4500M APU with Radeon(tm) HD Graphics 
	OptiFine Version: OptiFine_1.10.2_HD_U_D4
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13397 Compatibility Profile Context 15.200.1055.0
	OpenGlRenderer: AMD Radeon HD 7640G
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by Peekofwar** [comment]
I've disabled the feature for now.

**Comment by iChun** [comment]
Optifine is causing the crash

**Comment by Peekofwar** [comment]
Oh, I wasn't aware...
Edited the title so others can clearly see it. I hope you can fix this so that they play nicely. Optifine makes my game run better when I have issues with mods lagging my game.

**Comment by iChun** [comment]
Optifine issue

**Comment by m-riss** [comment]
This happens in the 1.18.2 version of optifine as well...
