### ISSUE TITLE
[1.10.2] [Portal Gun] Server Crash on Portal Creation

### ISSUE THREAD

**Issue by Unbansheee** [iChun/IssueTracker-Mods#64]
Server is currently running a custom modpack. I was testing the portal gun. On the creation of the second part of the portal, the server itself crashed, all clients were unaffected. Crash report is as follows:

https://pastebin.com/03gRWVc8

**Comment by iChun** [comment]
Fixed iChunUtil 6.3.1. https://github.com/iChun/iChunUtil/commit/148b79a877736103437fb4ca90a0a6034259f6c5
