### ISSUE TITLE
[1.10.2][GravityGun] Selecting empty hotbar slot doesn't ungrab block

### ISSUE THREAD

**Issue by EzerArch** [iChun/IssueTracker-Mods#65]
The GravityGun will not "ungrab" block or entity if the player selects an empty hotbar slot. The object gets stuck in front of the player.

The expected behavior: the GravityGun ungrabs whenever the player unselects the gun.

**Video:** https://youtu.be/tN92RHuSLwE (1st 50")

**Comment by iChun** [comment]
Not surprising I had to fix this for Portal Gun as well.

**Comment by iChun** [comment]
Fixed for GG 6.0.1
