### ISSUE TITLE
[Portal Gun] Crash Report "Description: Exception while updating neighbours"

### ISSUE THREAD

**Issue by Peekofwar** [iChun/IssueTracker-Mods#67]
I placed a portal on a wall, but, before Minecraft rendered it, [my game crashed,](http://domainofpeekofwar.weebly.com/uploads/3/8/3/5/38359671/modded_mc_crash_-_exception_while_updating_neighbours_-_ichun_portalgun_mod.txt)

Description: Exception while updating neighbours

**Comment by Peekofwar** [comment]
Game just crashed again with the same exception.

**Comment by iChun** [comment]
Should be fixed for PG 6.0.1. Please let me know if it's not fixed in that version
