### ISSUE TITLE
Server crash java.lang.NoClassDefFoundError: org/lwjgl/util/vector/Matrix4f

### ISSUE THREAD

**Issue by a-frenzy** [iChun/IssueTracker-Mods#68]
https://gist.github.com/frenzye/f4b02c50e87c6561e7f4c160fdf1ee54

**Comment by iChun** [comment]
Fixed iChunUtil 6.3.1. https://github.com/iChun/iChunUtil/commit/148b79a877736103437fb4ca90a0a6034259f6c5
