### ISSUE TITLE
[1.10.2] Server crash when when left clicking then right clicking to form 2nd portal.

### ISSUE THREAD

**Issue by StoneLegion** [iChun/IssueTracker-Mods#69]
https://pastebin.com/rnbTr8eW

When you activate 2nd portal boom :)

**Comment by iChun** [comment]
Kane! Of all people I would at least expect you to check for duplicate
issues first!

**Comment by StoneLegion** [comment]
I was being tired and lazy :(

Duplicate of 
#68 
#64 
#48 
#47 

Will close!

**Comment by iChun** [comment]
Oh God the 48 to 64 jump. I'm behind on issues.

**Comment by iChun** [comment]
Fixed iChunUtil 6.3.1. https://github.com/iChun/iChunUtil/commit/148b79a877736103437fb4ca90a0a6034259f6c5
