### ISSUE TITLE
1.10.2 [Portal Gun] Does not work on the server

### ISSUE THREAD

**Issue by TheTestMod** [iChun/IssueTracker-Mods#72]
Works fine in a single game, but does not work on the server.
Modpack in both cases alone
**Screenshots:**
![2017-04-22_01 39 28](https://cloud.githubusercontent.com/assets/27297260/25298474/d7914580-26fd-11e7-8045-acc0f86e77f9.png)
![2017-04-22_01 41 36](https://cloud.githubusercontent.com/assets/27297260/25298473/d7902d9e-26fd-11e7-840a-0442a3ee1d1d.png)
**Full modlist:**
BdLib (by bdew)
Calculator (by Ollie_Lansdell)
Tool Belt (by gigaherz)
Ender IO (by CrazyPants_MC)
CompatLayer (by McJty)
Ender Zoo (by CrazyPants_MC)
The One Probe (by McJty)
Refined Storage (by raoulvdberge)
Rustic (by thatguy3039)
Advanced Solar Panels (by Chocohead)
MCMultiPart (by amadornes)
FloodLights (by Keridos)
OMLib (by Keridos)
Extra Utilities (by RWTema)
Brandon's Core (by brandon3055)
Super Circuit Maker (by amadornes)
MultiStorage (by ShetiPhian)
Random Things (by lumien231)
ShetiPhianCore (by ShetiPhian)
Drones (by Vadis365)
Giacomo's Foundry (by Zacomat)
ZeroCore (by ZeroNoRyouki)
EnderCore (by tterrag1098)
TrueType Font Replacement (by CubeX2)
MineTweaker RecipeMaker (by DoubleDoorDevelopment)
Simple Covers (by bdew)
Redstone Paste (by FyberOptic)
MalisisCore (by Ordinastie)
Iron Backpacks (by gr8pefish)
CodeChicken Lib 1.8.+ (by covers1624)
BiblioCraft (by JDSinclair)
Practical Logistics 2 (by Ollie_Lansdell)
Animania (by Purplicious_Cow)
ArchitectureCraft (by gcewing)
Cyclic (by Lothrazar)
GraveStone Mod (by EuhDawson)
Gravity Gun (by iChun)
Baubles (by azanor)
LootBags (by Malorolam)
McJtyLib (by McJty)
OpenBlocks Elevator (by VsnGamer)
Iron Chests (by progwml6)
iChunUtil (by iChun)
Sonar Core (by Ollie_Lansdell)
SG Craft (by gcewing)
MalisisDoors (by Ordinastie)
JourneyMap (by techbrew)
Just Enough Items (JEI) (by mezz)
Just Enough Resources (JER) (by Way2muchnoise)
CraftTweaker (by jaredlll08)
OpenModularTurrets (by Poenjabiesous)
RFTools Control (by McJty)
Biomes O' Plenty (by Glitchfiend)
Laser Creeper Robot Dino Riders From Space (by Vadis365)
Draconic Evolution (by brandon3055)
Terraqueous (by ShetiPhian)
Epic Siege Mod (by Funwayguy)
Mod Name Tooltip (by mezz)
Water Power (by huanghongxun)
Industrial Craft (by Player)
Modular Forcefield System (by nekosune)
Dungeon Tactics (by PegBeard)
Slugs Eu energy converters (by _Slug)
Portal Gun (by iChun)
Extreme Reactors (by ZeroNoRyouki)
Gravitation Suite (by Chocohead)
Grue (by Shinoow)
NuclearCraft Mod (by TLJGames)
IvToolkit (by Ivorforce)
Pandora's Box (by Ivorforce)
FTBLib (by FTB)
FTB Utilities (by FTB)
Recurrent Complex (by Ivorforce)
RFTools (by McJty)
Inventory Tweaks (by Kobata)
Mouse Tweaks (by YaLTeR97)
Kaishi's Weapon Pack (by NoelRoadman)
Fence Overhaul (by The_WeatherPony)
LimeLib (by MrRiegel)
Furnus (by MrRiegel)
Grimoire of Gaia (by Silentine)
Chameleon (by jaquadro)
Storage Drawers (by jaquadro)
Reborn Core (by modmuss50)
Reborn Storage (by modmuss50)
Crossbows Mod (by CameronLow20)
Progressive Automation (by VanhalMinecraft)
Air Support (by Vadis365)
Aroma1997Core (by Aroma1997)
AromaBackup (by Aroma1997)
Morpheus (by Quetzi)
Chisel (by tterrag1098)
**PC:**
Lenovo z580 i5-3210 RAM 8g VC -gforce m630 2g

**Comment by iChun** [comment]
Can you elaborate a bit more?

**Comment by TheTestMod** [comment]
In the course of the day I'll take a video.
(Sorry for the machine translation)

**Comment by TheTestMod** [comment]
Hi!
Video bug: [https://www.youtube.com/watch?v=A5fmhveKS9I&feature=youtu.be](url)

**Comment by sharkck** [comment]
I'm having this same issue as well

**Comment by iChun** [comment]
Fixed in PG 6.0.1
