### ISSUE TITLE
[Issue][Portalgun] Breaking Issue with RFTools' Elevator and Portalgun

### ISSUE THREAD

**Issue by accessdenied0** [iChun/IssueTracker-Mods#73]
Hello @iChun 

I sadly have to report an issue with the Portalgun mod.

**Minecraft details:**
Mc-version: 1.10.1
Forge-version: 12.18.3.2228
Mod-versions: Portalgun (6.0.0) , RFTools (6.00), Mcjtylib (1.1x-2.3.11), Compatlayer (1.10-0.2.5)

**Issue details:**
While I had the mod Portalgun (6.0.0) installed, my client crashed every time I tried to break the Elevator-Block from RFTools (6.00). (An additional problem could be NotEnoughID's)

**Crash report:**
https://pastebin.com/Bx1hmbth

I hope I didn't forget anything,

access_denied

**Comment by iChun** [comment]
Turns out I'm accidentally spawning twice the number of particles and it's causing issues and crashes. I've fixed that now and hopefully that fix fixes this too (Code that crashes isn't even being called anymore). Try it out in PortalGun 6.0.1 + iChunUtil 6.3.2
