### ISSUE TITLE
[1.10.2] [Portal Gun] Portal not rendering correctly

### ISSUE THREAD

**Issue by Derpchop** [iChun/IssueTracker-Mods#76]
http://imgur.com/a/PFYri
When only one portal is placed, it uses the opened portal render
And it doesn't have any color

**Comment by iChun** [comment]
There is a fix that I implemented for PG 6.0.1 regarding the shaders. Can you try that out (when released) and let me know if this is still an issue?

**Comment by Derpchop** [comment]
ok thanks

**Comment by iChun** [comment]
PG 6.0.1 is now out. I'm gonna close this in the meantime but please do let me know if the black portals are fixed.
