### ISSUE TITLE
[1.10.2] portal gun

### ISSUE THREAD

**Issue by audenga** [iChun/IssueTracker-Mods#80]
not sure if im doing anything wrong but i cant seem to use the portal part on my server

v6.0.1

**Comment by iChun** [comment]
What versions?

**Comment by audenga** [comment]
v6.0.1
i edited that in after i realized i didn't state it

**Comment by iChun** [comment]
Can you elaborate more? I can help you with such little information you've given. What version of iChunUtil?

**Comment by audenga** [comment]
not sure what happened, started up computer today, jumped on to get a recording of whats going on, and its now working, sometimes i dont get minecraft
