### ISSUE TITLE
[1.10.2] [PortalGun]   Cant use Portalguns with optifine installed

### ISSUE THREAD

**Issue by ghostbuster3210** [iChun/IssueTracker-Mods#81]
PortalGuns is a really performance heavy mod,  especially when you're looking through a portal,  

so the natural solution would be to use optifine right?   but optifine is out of the question,   with optifine installed,  it took my MC from a nice 105 fps to a solid 40 just from selecting the portal gun in my hotbar
(tried it again without optifine and this didnt happen)
but while some players could look over that,   if you shoot a portal with optifine installed,  the game crashes when you place the second portal down and they link.

**Comment by iChun** [comment]
Well, if you want to use Optifine with PG, report the issue over to them. They're breaking normal modded forge so it's not something for me to fix my end.
