### ISSUE TITLE
Minecraft crashes before loading onto title screen with iChunUtil or the new PortalGun mod

### ISSUE THREAD

**Issue by hexteq** [iChun/IssueTracker-Mods#89]
In 1.10.2 forge, Minecraft loads into the menu fine without either iChunUtil or the PortalGun mod, or else it will crash. Please give me help, I seem to be the only one experiencing this problem. Here's the error message:

The game crashed whilst rendering screen
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen

Thanks in advance.

**Comment by GirafiStudios** [comment]
Please pastebin/gist the crash report. iChun can't do anything to fix this, with the current information you have given.

**Comment by hexteq** [comment]
https://pastebin.com/GqgL8zYx
There. I don't know how these crash report things work so do your magic

**Comment by Artthefusky** [comment]
https://pastebin.com/KNAtdxiU I have the same problem too

**Comment by DrTrap909** [comment]
Same Problem
https://pastebin.com/Q1suBKvJ NVM EVERYONE UPDATE FORGE 1.10.2 TO FULL NOT RECOMENDED

**Comment by Artthefusky** [comment]
DrTrap909
Do you mean the latest version?

**Comment by DrTrap909** [comment]
like latest forge 1.10.2

**Comment by DrTrap909** [comment]
just go to forge and download not the recommended 1.10.2 but the latest or whatever it says
