### ISSUE TITLE
Missing items / Broken portalgun versions

### ISSUE THREAD

**Issue by 57331Fury** [iChun/IssueTracker-Mods#91]
Okay, so I was using Portalgun 1.10.2-6.0.0 and iChunUtil-1.10.2-6.3.0, and when searching in JEI / NEI for @portal all I got was 8 items in total, 6 portal guns, ender pearl dust and a miniature black hole. Crafting a portal gun did not give me the portal gun that it linked to in JEI, but a 'Newly crafted portal gun' which did nothing at all, and could not be crafted with dyes /porkchops etc. Searching google for "Newly crafted portal gun" brought up only 2 results, and neither refered to the in-game item. I have now updated to to the latest versons of both Portalgun (1.10.2-6.0.1) and iChunUtil (1.10.2-6.3.2), and finally the newly crafted portal gun does actually work. However there is still none of the other items shown in various videos that are supposedly in the 1.10.2 mod (It still only shows the same 8 items), such as the portal gun pedestal, weighted storage cube, or longfall boots, and there is zero documentation on the internet for anything to do with this on 1.10.2. Old wiki`s crafting recipes for these items also do not work (Just incase the items were just hidden from JEI)

**Comment by iChun** [comment]
Have you considered updating? There's a newer version available for both
mods.

**Comment by iChun** [comment]
Oh hang on just read the rest of your message. The mod was rewritten and a
lot of the old items are not in the rewrite. The May be added on in the
future. There isn't proper documentation on the mod just yet but it's
simple enough to figure out (I hope)

**Comment by 57331Fury** [comment]
Thanks for the response. I probably should have written that with a clearer head, but was just getting a bit frustrated. Using the newer version has sorted out the actual portalgun issue yes, and now I know that I am not actually missing items that are supposed to be there has cleared it up. Its just confusing to see videos on Youtube with people supposedly on 1.10 using the other items.
